export const strings = {
  appName: 'ALive',
  splash: {
    tagline: 'Live Streaming & Voice Chat',
  },
  login: {
    welcome: 'Welcome back! 👋',
    subtitle: 'Sign in to continue your live streaming journey.',
    emailLabel: 'Email ID or Phone Number',
    emailPlaceholder: 'Enter Registered Email or Phone No.',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Login',
    orContinue: 'or continue with',
    googleButton: 'Continue with Google',
    facebookButton: 'Continue with Facebook',
    signUpPrompt: "Don't have an account?",
    signUpLink: 'Sign Up',
  },
  home: {
    searchPlaceholder: 'Search streamer...',
    tabs: {
      stream: 'Stream',
      hot: 'Hot',
      follow: 'Follow',
    },
    carouselTitle: 'Top Live Creators',
    trendingStatus: 'Trending Live',
    emptyTitle: 'No Followed Creators',
    emptyText: "You aren't following anyone yet. Tap '+ Follow' on live cards to keep up with your favorite streamers.",
    exploreButton: 'Explore Live Feeds',
  },
  modal: {
    live: 'LIVE',
    watching: 'watching now',
    trendingMeter: 'Trending Meter',
    bio: 'Streaming live! Welcome to the channel. Feel free to join, interact, and show your support!',
    followCreator: 'Follow Creator',
    following: 'Following',
  },
  profile: {
    title: 'Profile',
    followers: 'Followers',
    following: 'Following',
    status: 'Status',
    level: 'Level 3',
    accountSettings: 'Account Settings',
    privacySecurity: 'Privacy & Security',
    helpSupport: 'Help & Support',
    logout: 'Log Out',
    logoutTitle: 'Log Out',
    logoutConfirm: 'Are you sure you want to log out of your account?',
    cancel: 'Cancel',
  },
};
